services:
  builder:
    build:
      context: .
      dockerfile: Build.Dockerfile
    container_name: builder
    volumes:
      - ~/.m2/:/root/.m2/
      - ./:/src/
      - ./builder-docker-entrypoint.sh:/docker-entrypoint.sh
    working_dir: /src
    entrypoint: /docker-entrypoint.sh
    networks:
      - gazetteer

  tomcat:
    container_name: tomcat
    image: tomcat:9.0-jdk11
    depends_on:
      mongodb:
        condition: service_started
      elasticsearch:
        condition: service_started
      builder:
        condition: service_healthy
        restart: true
    volumes:
      - ./TOMCAT/:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    networks:
      - gazetteer

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    volumes:
      - ./mongo/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./src/test/resources:/docker-entrypoint-initdb.d/data
    environment:
      MONGO_INITDB_DATABASE: gazetteer
    ports:
      - 27017:27017
    # entrypoint: /docker-entrypoint.sh
    networks:
      - gazetteer

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.7.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      # - cluster.name=gazetteer.dainst.org
    ports:
      - 9200:9200
    networks:
      - gazetteer

  elasticsearch-init:
    container_name: gazetteer_elasticsearch_init
    image: elasticsearch:6.7.1
    depends_on:
      - elasticsearch
    volumes:
      - ./elasticsearch-init/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./src/main/resources/es/_template/place_template_new.json:/mappings/place_template.json
    entrypoint: /docker-entrypoint.sh
    environment:
      - ELASTICSEARCH_CONTAINER_NAME=elasticsearch
    networks:
      - gazetteer

volumes:
  esdata:
    driver: local

networks:
  gazetteer:
