services:
  tomcat:
    build:
      context: .
      dockerfile: Tomcat.Dockerfile
    container_name: tomcat
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      # Example environment variables your app could use
      - MONGO_URI=mongodb://mongodb:27017/myapp
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - gazetteer

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    # volumes:
    #   - ./mongo/docker-entrypoint.sh:/docker-entrypoint.sh
    #   - ./src/test/resources:/docker-entrypoint-initdb.d/data
    # environment:
    #   MONGO_INITDB_DATABASE: gazetteer
    ports:
      - 27017:27017
    # entrypoint: /docker-entrypoint.sh
    networks:
      - gazetteer

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.7.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      # - cluster.name=gazetteer.dainst.org
    ports:
      - 9200:9200
    networks:
      - gazetteer

  elasticsearch-init:
    container_name: gazetteer_elasticsearch_init
    image: elasticsearch:6.7.1
    depends_on:
      - elasticsearch
    volumes:
      - ./elasticsearch-init/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./src/main/resources/es/_template/place_template_new.json:/mappings/place_template.json
    entrypoint: /docker-entrypoint.sh
    environment:
      - ELASTICSEARCH_CONTAINER_NAME=elasticsearch
    networks:
      - gazetteer

volumes:
  esdata:
    driver: local

networks:
  gazetteer:
